# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OPV_Designer.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.setEnabled(True)
        Form.resize(1366, 738)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1366, 738))
        Form.setMaximumSize(QtCore.QSize(1366, 738))
        Form.setStyleSheet("background-color:rgb(212, 208, 200)")
        self.label_CAG = QtWidgets.QLabel(Form)
        self.label_CAG.setGeometry(QtCore.QRect(210, 160, 1111, 581))
        self.label_CAG.setAutoFillBackground(False)
        self.label_CAG.setText("")
        self.label_CAG.setPixmap(QtGui.QPixmap("CAG - Python.PNG"))
        self.label_CAG.setObjectName("label_CAG")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(300, 430, 72, 16))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.text_tempRet = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.text_tempRet.setContentsMargins(0, 0, 0, 0)
        self.text_tempRet.setObjectName("text_tempRet")
        self.label_textTemp = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_textTemp.setFont(font)
        self.label_textTemp.setObjectName("label_textTemp")
        self.text_tempRet.addWidget(self.label_textTemp)
        self.label_tempValor = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_tempValor.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_tempValor.setFont(font)
        self.label_tempValor.setObjectName("label_tempValor")
        self.text_tempRet.addWidget(self.label_tempValor)
        self.label_textC = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_textC.setFont(font)
        self.label_textC.setObjectName("label_textC")
        self.text_tempRet.addWidget(self.label_textC)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(1120, 420, 72, 16))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.text_tempIns = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.text_tempIns.setContentsMargins(0, 0, 0, 0)
        self.text_tempIns.setObjectName("text_tempIns")
        self.label_textTemp_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_textTemp_2.setFont(font)
        self.label_textTemp_2.setObjectName("label_textTemp_2")
        self.text_tempIns.addWidget(self.label_textTemp_2)
        self.label_tempValor_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_tempValor_2.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_tempValor_2.setFont(font)
        self.label_tempValor_2.setObjectName("label_tempValor_2")
        self.text_tempIns.addWidget(self.label_tempValor_2)
        self.label_textC_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_textC_2.setFont(font)
        self.label_textC_2.setObjectName("label_textC_2")
        self.text_tempIns.addWidget(self.label_textC_2)
        self.formLayoutWidget = QtWidgets.QWidget(Form)
        self.formLayoutWidget.setGeometry(QtCore.QRect(430, 270, 104, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.text_BAGP01 = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.text_BAGP01.setContentsMargins(0, 0, 0, 0)
        self.text_BAGP01.setObjectName("text_BAGP01")
        self.label_Comando = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Comando.setFont(font)
        self.label_Comando.setObjectName("label_Comando")
        self.text_BAGP01.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Comando)
        self.label_Estado = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Estado.setFont(font)
        self.label_Estado.setObjectName("label_Estado")
        self.text_BAGP01.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Estado)
        self.label_Falha = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Falha.setFont(font)
        self.label_Falha.setObjectName("label_Falha")
        self.text_BAGP01.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_Falha)
        self.label_LR = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_LR.setFont(font)
        self.label_LR.setObjectName("label_LR")
        self.text_BAGP01.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_LR)
        self.text_LR = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.text_LR.setFont(font)
        self.text_LR.setObjectName("text_LR")
        self.text_BAGP01.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.text_LR)
        self.label_gray = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_gray.setText("")
        self.label_gray.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray.setObjectName("label_gray")
        self.text_BAGP01.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_gray)
        self.label_gray_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_gray_2.setText("")
        self.label_gray_2.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_2.setObjectName("label_gray_2")
        self.text_BAGP01.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_gray_2)
        self.label_gray_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_gray_3.setText("")
        self.label_gray_3.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_3.setObjectName("label_gray_3")
        self.text_BAGP01.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_gray_3)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(430, 450, 104, 91))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.text_BAGP02 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.text_BAGP02.setContentsMargins(0, 0, 0, 0)
        self.text_BAGP02.setObjectName("text_BAGP02")
        self.label_Comando_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Comando_5.setFont(font)
        self.label_Comando_5.setObjectName("label_Comando_5")
        self.text_BAGP02.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Comando_5)
        self.label_Estado_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Estado_5.setFont(font)
        self.label_Estado_5.setObjectName("label_Estado_5")
        self.text_BAGP02.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Estado_5)
        self.label_Falha_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Falha_5.setFont(font)
        self.label_Falha_5.setObjectName("label_Falha_5")
        self.text_BAGP02.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_Falha_5)
        self.label_LR_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_LR_4.setFont(font)
        self.label_LR_4.setObjectName("label_LR_4")
        self.text_BAGP02.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_LR_4)
        self.text_LR_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.text_LR_4.setFont(font)
        self.text_LR_4.setObjectName("text_LR_4")
        self.text_BAGP02.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.text_LR_4)
        self.label_gray_5 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_gray_5.setText("")
        self.label_gray_5.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_5.setObjectName("label_gray_5")
        self.text_BAGP02.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_gray_5)
        self.label_gray_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_gray_6.setText("")
        self.label_gray_6.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_6.setObjectName("label_gray_6")
        self.text_BAGP02.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_gray_6)
        self.label_gray_4 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_gray_4.setText("")
        self.label_gray_4.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_4.setObjectName("label_gray_4")
        self.text_BAGP02.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_gray_4)
        self.formLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(430, 610, 104, 91))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.text_BAGPR = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.text_BAGPR.setContentsMargins(0, 0, 0, 0)
        self.text_BAGPR.setObjectName("text_BAGPR")
        self.label_Comando_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Comando_7.setFont(font)
        self.label_Comando_7.setObjectName("label_Comando_7")
        self.text_BAGPR.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Comando_7)
        self.label_gray_8 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_gray_8.setText("")
        self.label_gray_8.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_8.setObjectName("label_gray_8")
        self.text_BAGPR.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_gray_8)
        self.label_Estado_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Estado_7.setFont(font)
        self.label_Estado_7.setObjectName("label_Estado_7")
        self.text_BAGPR.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Estado_7)
        self.label_gray_9 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_gray_9.setText("")
        self.label_gray_9.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_9.setObjectName("label_gray_9")
        self.text_BAGPR.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_gray_9)
        self.label_Falha_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Falha_7.setFont(font)
        self.label_Falha_7.setObjectName("label_Falha_7")
        self.text_BAGPR.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_Falha_7)
        self.label_gray_7 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.label_gray_7.setText("")
        self.label_gray_7.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_7.setObjectName("label_gray_7")
        self.text_BAGPR.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_gray_7)
        self.label_LR_5 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_LR_5.setFont(font)
        self.label_LR_5.setObjectName("label_LR_5")
        self.text_BAGPR.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_LR_5)
        self.text_LR_5 = QtWidgets.QLabel(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.text_LR_5.setFont(font)
        self.text_LR_5.setObjectName("text_LR_5")
        self.text_BAGPR.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.text_LR_5)
        self.formLayoutWidget_4 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(800, 350, 80, 71))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.text_Chiller01 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.text_Chiller01.setContentsMargins(0, 0, 0, 0)
        self.text_Chiller01.setObjectName("text_Chiller01")
        self.label_Comando_8 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Comando_8.setFont(font)
        self.label_Comando_8.setObjectName("label_Comando_8")
        self.text_Chiller01.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Comando_8)
        self.label_Estado_8 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Estado_8.setFont(font)
        self.label_Estado_8.setObjectName("label_Estado_8")
        self.text_Chiller01.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Estado_8)
        self.label_Falha_8 = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Falha_8.setFont(font)
        self.label_Falha_8.setObjectName("label_Falha_8")
        self.text_Chiller01.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_Falha_8)
        self.label_gray_10 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_gray_10.setText("")
        self.label_gray_10.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_10.setObjectName("label_gray_10")
        self.text_Chiller01.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_gray_10)
        self.label_gray_11 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_gray_11.setText("")
        self.label_gray_11.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_11.setObjectName("label_gray_11")
        self.text_Chiller01.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_gray_11)
        self.label_gray_12 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_gray_12.setText("")
        self.label_gray_12.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_12.setObjectName("label_gray_12")
        self.text_Chiller01.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_gray_12)
        self.formLayoutWidget_5 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(800, 580, 80, 71))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.text_Chiller02 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.text_Chiller02.setContentsMargins(0, 0, 0, 0)
        self.text_Chiller02.setObjectName("text_Chiller02")
        self.label_Comando_10 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Comando_10.setFont(font)
        self.label_Comando_10.setObjectName("label_Comando_10")
        self.text_Chiller02.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Comando_10)
        self.label_Estado_10 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Estado_10.setFont(font)
        self.label_Estado_10.setObjectName("label_Estado_10")
        self.text_Chiller02.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Estado_10)
        self.label_Falha_10 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Falha_10.setFont(font)
        self.label_Falha_10.setObjectName("label_Falha_10")
        self.text_Chiller02.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_Falha_10)
        self.label_gray_14 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_gray_14.setText("")
        self.label_gray_14.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_14.setObjectName("label_gray_14")
        self.text_Chiller02.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_gray_14)
        self.label_gray_13 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_gray_13.setText("")
        self.label_gray_13.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_13.setObjectName("label_gray_13")
        self.text_Chiller02.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_gray_13)
        self.label_gray_15 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_gray_15.setText("")
        self.label_gray_15.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_15.setObjectName("label_gray_15")
        self.text_Chiller02.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_gray_15)
        self.formLayoutWidget_6 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(960, 320, 80, 71))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.text_VAG01 = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.text_VAG01.setContentsMargins(0, 0, 0, 0)
        self.text_VAG01.setObjectName("text_VAG01")
        self.label_Comando_11 = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Comando_11.setFont(font)
        self.label_Comando_11.setObjectName("label_Comando_11")
        self.text_VAG01.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Comando_11)
        self.label_Estado_11 = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Estado_11.setFont(font)
        self.label_Estado_11.setObjectName("label_Estado_11")
        self.text_VAG01.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Estado_11)
        self.label_Falha_11 = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Falha_11.setFont(font)
        self.label_Falha_11.setObjectName("label_Falha_11")
        self.text_VAG01.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_Falha_11)
        self.label_gray_18 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_gray_18.setText("")
        self.label_gray_18.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_18.setObjectName("label_gray_18")
        self.text_VAG01.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_gray_18)
        self.label_gray_16 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_gray_16.setText("")
        self.label_gray_16.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_16.setObjectName("label_gray_16")
        self.text_VAG01.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_gray_16)
        self.label_gray_17 = QtWidgets.QLabel(self.formLayoutWidget_6)
        self.label_gray_17.setText("")
        self.label_gray_17.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_17.setObjectName("label_gray_17")
        self.text_VAG01.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_gray_17)
        self.formLayoutWidget_7 = QtWidgets.QWidget(Form)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(960, 550, 80, 71))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.text_VAG02 = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.text_VAG02.setContentsMargins(0, 0, 0, 0)
        self.text_VAG02.setObjectName("text_VAG02")
        self.label_Comando_12 = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Comando_12.setFont(font)
        self.label_Comando_12.setObjectName("label_Comando_12")
        self.text_VAG02.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_Comando_12)
        self.label_Estado_12 = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Estado_12.setFont(font)
        self.label_Estado_12.setObjectName("label_Estado_12")
        self.text_VAG02.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_Estado_12)
        self.label_Falha_12 = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_Falha_12.setFont(font)
        self.label_Falha_12.setObjectName("label_Falha_12")
        self.text_VAG02.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_Falha_12)
        self.label_gray_21 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_gray_21.setText("")
        self.label_gray_21.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_21.setObjectName("label_gray_21")
        self.text_VAG02.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_gray_21)
        self.label_gray_19 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_gray_19.setText("")
        self.label_gray_19.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_19.setObjectName("label_gray_19")
        self.text_VAG02.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_gray_19)
        self.label_gray_20 = QtWidgets.QLabel(self.formLayoutWidget_7)
        self.label_gray_20.setText("")
        self.label_gray_20.setPixmap(QtGui.QPixmap("gray_led.png"))
        self.label_gray_20.setObjectName("label_gray_20")
        self.text_VAG02.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_gray_20)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1264, 590, 81, 23))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(1264, 620, 81, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1264, 650, 81, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(1264, 680, 81, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 234, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 4, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 5, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 5, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 3, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout.addWidget(self.label_18)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout.addWidget(self.label_16)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout.addWidget(self.label_20)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout.addWidget(self.label_21)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_2.addWidget(self.label_22)
        self.label_23 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_2.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_2.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_2.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_2.addWidget(self.label_26)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 6, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 130, 171, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_CAG.raise_()
        self.horizontalLayoutWidget.raise_()
        self.horizontalLayoutWidget_2.raise_()
        self.formLayoutWidget.raise_()
        self.formLayoutWidget_2.raise_()
        self.formLayoutWidget_3.raise_()
        self.formLayoutWidget_4.raise_()
        self.formLayoutWidget_5.raise_()
        self.formLayoutWidget_6.raise_()
        self.formLayoutWidget_7.raise_()
        self.gridLayoutWidget.raise_()
        self.pushButton_5.raise_()
        self.pushButton_3.raise_()
        self.pushButton.raise_()
        self.pushButton_4.raise_()
        self.pushButton_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "OPV - Operador Virtual"))
        self.label_textTemp.setText(_translate("Form", "Temp:"))
        self.label_tempValor.setText(_translate("Form", "00"))
        self.label_textC.setText(_translate("Form", "°C"))
        self.label_textTemp_2.setText(_translate("Form", "Temp:"))
        self.label_tempValor_2.setText(_translate("Form", "00"))
        self.label_textC_2.setText(_translate("Form", "°C"))
        self.label_Comando.setText(_translate("Form", "Comando"))
        self.label_Estado.setText(_translate("Form", "Estado"))
        self.label_Falha.setText(_translate("Form", "Falha"))
        self.label_LR.setText(_translate("Form", "L/R"))
        self.text_LR.setText(_translate("Form", "Remoto"))
        self.label_Comando_5.setText(_translate("Form", "Comando"))
        self.label_Estado_5.setText(_translate("Form", "Estado"))
        self.label_Falha_5.setText(_translate("Form", "Falha"))
        self.label_LR_4.setText(_translate("Form", "L/R"))
        self.text_LR_4.setText(_translate("Form", "Remoto"))
        self.label_Comando_7.setText(_translate("Form", "Comando"))
        self.label_Estado_7.setText(_translate("Form", "Estado"))
        self.label_Falha_7.setText(_translate("Form", "Falha"))
        self.label_LR_5.setText(_translate("Form", "L/R"))
        self.text_LR_5.setText(_translate("Form", "Remoto"))
        self.label_Comando_8.setText(_translate("Form", "Comando"))
        self.label_Estado_8.setText(_translate("Form", "Estado"))
        self.label_Falha_8.setText(_translate("Form", "Falha"))
        self.label_Comando_10.setText(_translate("Form", "Comando"))
        self.label_Estado_10.setText(_translate("Form", "Estado"))
        self.label_Falha_10.setText(_translate("Form", "Falha"))
        self.label_Comando_11.setText(_translate("Form", "Comando"))
        self.label_Estado_11.setText(_translate("Form", "Estado"))
        self.label_Falha_11.setText(_translate("Form", "Falha"))
        self.label_Comando_12.setText(_translate("Form", "Comando"))
        self.label_Estado_12.setText(_translate("Form", "Estado"))
        self.label_Falha_12.setText(_translate("Form", "Falha"))
        self.pushButton.setText(_translate("Form", "Falha BAG01"))
        self.pushButton_2.setText(_translate("Form", "Falha BAG02"))
        self.pushButton_3.setText(_translate("Form", "Falha Chiller 01"))
        self.pushButton_4.setText(_translate("Form", "Falha Chiller 02"))
        self.label_7.setText(_translate("Form", "Temperatura"))
        self.label_8.setText(_translate("Form", "Temperatura Máxima"))
        self.label_6.setText(_translate("Form", "Horário"))
        self.label_3.setText(_translate("Form", "Data"))
        self.label_2.setText(_translate("Form", "xxxxxxxxxxxx"))
        self.label.setText(_translate("Form", "Localização"))
        self.label_9.setText(_translate("Form", "Temperatura Minima"))
        self.label_10.setText(_translate("Form", "Umidade"))
        self.label_11.setText(_translate("Form", "xx"))
        self.label_12.setText(_translate("Form", "xx"))
        self.label_13.setText(_translate("Form", "°C"))
        self.label_14.setText(_translate("Form", "xx"))
        self.label_15.setText(_translate("Form", "°C"))
        self.label_5.setText(_translate("Form", "xx"))
        self.label_17.setText(_translate("Form", "°C"))
        self.label_18.setText(_translate("Form", "hh"))
        self.label_16.setText(_translate("Form", ":"))
        self.label_19.setText(_translate("Form", "mm"))
        self.label_20.setText(_translate("Form", ":"))
        self.label_21.setText(_translate("Form", "ss"))
        self.label_22.setText(_translate("Form", "dd"))
        self.label_23.setText(_translate("Form", "/"))
        self.label_24.setText(_translate("Form", "mm"))
        self.label_25.setText(_translate("Form", "/"))
        self.label_26.setText(_translate("Form", "aaaa"))
        self.label_27.setText(_translate("Form", "%"))
        self.pushButton_5.setText(_translate("Form", "Partida da CAG"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

